sudo: required
services:
    - docker
before_install:
    - docker build -f Dockerfile.dev -t vamckrishna/react-frontend .
script:
    - docker run -e CI=true vamckrishna/react-frontend npm test -- --coverage
language: generic