version: '3'
services:
    dev:
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        volumes: 
            - /app/react-frontend/node_modules
            - ./:/app/react-frontend
        ports: 
            - 3000:3000
        stdin_open: true
    test:
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        volumes: 
            - /app/react-frontend/node_modules
            - ./:/app/react-frontend
        command: ["npm", "test"]
            